{
    "name": "SG NRIC verification",
    "version": "17.0.1.0.0",
    "license": "LGPL-3",
    "depends": ['l10n_sg_hr_payroll'],
    "author": "Serpent Consulting Services Pvt. Ltd.",
    "maintainer": "Serpent Consulting Services Pvt. Ltd.",
    "website": "http://www.serpentcs.com",
    "category": "Human Resources",
    "description": """Validate NRIC number""",
    "summary": """This module is used to validate Employee's NRIC number""",
    'installable': True,
    'auto_install': False,
    'application': False,
    "price": 39,
    "currency": 'EUR',
}
