# -*- coding: utf-8 -*-
{
    "name": "Iconn User & Access Setup",
    "summary": "Seed internal users and role-based access groups for Iconn",
    "version": "17.0.1.0.0",
    "author": "Iconn",
    "category": "Customization",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "contacts",
        "crm",
        "sale_management",
        "purchase",
        "stock",
        "account",
        "hr",
        "hr_holidays",
        "hr_expense",
        "project",
        "iconn_account",
        "quality_control_oca",
    ],
    "data": [
        "data/iconn_role_groups.xml",
        "data/iconn_users.xml",
        "data/iconn_user_group_assignment.xml",
        "data/iconn_org_chart_groups.xml",
        "data/iconn_org_chart_assignments.xml",
        "data/iconn_org_chart_legacy_membership_cleanup.xml",
        "data/iconn_partner_backfill.xml",
        "views/res_partner_views.xml",
        "security/iconn_record_rules.xml",
    ],
    "installable": True,
    "application": False,
}
