[options]
addons_path = /mnt/extra-addons/addons-community,/mnt/extra-addons/iconn,/mnt/extra-addons/th,
admin_passwd = $pbkdf2-sha512$600000$CIFwjhEiRKjVOqeU0loLgQ$..IgXXBNjd1/hL9/4zvc7.BRZgOTaRW2xbKulQSY2Dz5AbXPxkRFwHxsdmvqPpJKA5q0v.9UjDevBgKu.BDa/w
log_level = debug
logfile = /var/log/odoo/odoo.log
