from . import res_company
from . import res_config_settings
from . import res_users
from . import res_partner
from . import account_move
from . import sale
from . import icon_sales_history
from . import crm_lead
from . import product
from . import stock_picking
from . import purchase
from . import stock_move
from . import res_currency
from . import stock_location
