# See LICENSE file for full copyright and licensing details.

{
    'name': 'Account Financial Accounting Reports',
    'summary': '''Standard Account Financial Accounting Reports''',
'version': '17.0.1.0.0',    'description': '''
    Standard Account Financial Accounting Reports''',
    "license": "LGPL-3",
    'description': '''Standard Account Reports of Balance Sheet, Profit and
     Loss, Trial Balance, Partner Ledger, Partner Aging report
     Customer and Supplier Aging report, Tax Report, Journal Audit Report
     with pdf and excel formats with multiple filters''',
    'category': 'Accounting',
    'author': 'Serpent Consulting Services Pvt. Ltd.',
    'maintainer': 'Serpent Consulting Services Pvt. Ltd.',
    'website': 'http://www.serpentcs.com',
    'depends': ['account'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/web_layout.xml',
        'views/account_menuitem.xml',
        'views/account_view.xml',
        'views/report_journal.xml',
        'wizard/account_common_report_compat_view.xml',
        'wizard/account_report_print_journal_view.xml',
        'views/gstreturn_f5_report_view.xml',
        'wizard/gstreturn_view.xml',
        'views/gstreturn_f7_report_view.xml',
        'wizard/gstreturnf7_view.xml',
        'views/account_report.xml',
        'views/report_overdue.xml',
        'wizard/account_report_aged_partner_balance_view.xml',
        'views/report_agedpartnerbalance.xml',
        'wizard/account_report_partner_ledger_view.xml',
        'views/report_partnerledger.xml',
        'wizard/account_report_general_ledger_view.xml',
        'views/report_generalledger.xml',
        'wizard/account_report_trial_balance_view.xml',
        'views/report_trialbalance.xml',
        'wizard/account_financial_report_view.xml',
        'views/report_financial.xml',
        'views/account_report_payment_receipt_templates.xml',
        'views/report_tax.xml',
        'wizard/account_report_tax_view.xml',
        'wizard/account_report_template_wizard.xml',
        'views/account_balance_full_temp.xml',
        'views/account_financial_report_view.xml',
        'views/account_full_qtr_cols.xml',
        'views/account_full_13_cols.xml',

    ],
    'images': ['static/description/banner.png'],
    'installable': True,
    'auto_install': False,
    'application': False,
    'price': 99,
    'currency': 'EUR',
}
